### ISSUE TITLE
define unit stats

### ISSUE THREAD

**Issue by riftgarret** [riftgarret/ludum#18]
Define stats so that combat stats can be influenced by base generic stats.
similar to
![image](https://user-images.githubusercontent.com/444349/46852650-8ab73200-cdb0-11e8-93a6-8035c0cbae97.png)

**Comment by RiceGnat** [comment]
jrpg flavor
![image](https://user-images.githubusercontent.com/3154593/46852758-9f4ff600-cdc1-11e8-874b-61627fac3f30.png)

**Comment by riftgarret** [comment]
It would be nice if we could calculate HPs (among other stats) in the fashion like so:
so that our base HPs could be, ```LEVEL * (HP_SCALE + CON_FORMULA) + HP_BUFF```

* **CON_FORMULA** similar to DnD: 0 at CON = 10, +3 at 18, but we'll use a float number to get gains per poinnt instead of 1 integer every two values.
* **HP_SCALE** This should probably be defined by class, berserkers would have like 100, where wizards would have like 30 as a extreme example. 
* **LEVEL** duh
* **HP_BUFF** This should aggregate values such that we can place buffs or equipment that may adjust this value

**Comment by riftgarret** [comment]
Closing this ticket as its better clarified in https://github.com/riftgarret/ludum/issues/59
